name: new-pipeline
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pandas
  - numpy
  - scikit-learn
  - geopandas
  - shapely
  - pyproj
  - matplotlib
  - pyarrow
  - networkx
  - tqdm
  - pip:
      - torch
      - transformers
      - datasets
      - huggingface_hub
      - peft
      - node2vec
      - gensim
